var getTodos = async () => {
    var res = await fetch("https://jsonplaceholder.typicode.com/todos");
    var todosFull = await res.json();
    var todos = todosFull.slice(0, 20);
    console.log("Todos loaded")
    return todos;
}

document.addEventListener("DOMContentLoaded", async function () {
    const hamburger = document.getElementById("hamburger");
    hamburger.addEventListener("click", function () {
        if (this.classList.contains("open")) {
            this.classList.remove("open")
        } else {
            this.classList.add("open")
        }

    })
    console.log("Hamburger loaded");
    todos = await getTodos();
    todos.forEach((todo) => {

        document.getElementById("autogenerated").insertAdjacentHTML(
            `
        <div class="todoItem">
        <div class="checkDescription">
          <div class="todoCheck"><input type="checkbox" defaultchecked="false" class="checkCircle"></input></div>
          <div class="todoDescription">
            <span class="todoText">${todo.title}</span>
          </div>
        </div>

        <div class="todoDelete">
          <div class="deleteIconContainer">
            <img
              class="deleteIcon"
              src="/public/images/trash.png"
              alt=""
            />
          </div>
          <div class="deleteTooltip"></div>
        </div>
      </div>
        `
        )
    })

    console.log()




});